syntax = "proto3";

package qsoripper.services;

option csharp_namespace = "QsoRipper.Services";

import "services/abort_winkeyer_client_request.proto";
import "services/abort_winkeyer_client_response.proto";
import "services/cancel_winkeyer_job_request.proto";
import "services/cancel_winkeyer_job_response.proto";
import "services/get_winkeyer_broker_status_request.proto";
import "services/get_winkeyer_broker_status_response.proto";
import "services/send_winkeyer_text_request.proto";
import "services/send_winkeyer_text_response.proto";
import "services/set_winkeyer_broker_speed_request.proto";
import "services/set_winkeyer_broker_speed_response.proto";
import "services/stream_winkeyer_events_request.proto";
import "services/stream_winkeyer_events_response.proto";

service WinkeyerBrokerService {
  rpc GetStatus(WinkeyerBrokerServiceGetStatusRequest) returns (WinkeyerBrokerServiceGetStatusResponse);
  rpc SendText(WinkeyerBrokerServiceSendTextRequest) returns (WinkeyerBrokerServiceSendTextResponse);
  rpc CancelJob(WinkeyerBrokerServiceCancelJobRequest) returns (WinkeyerBrokerServiceCancelJobResponse);
  rpc AbortClient(WinkeyerBrokerServiceAbortClientRequest) returns (WinkeyerBrokerServiceAbortClientResponse);
  rpc SetSpeed(WinkeyerBrokerServiceSetSpeedRequest) returns (WinkeyerBrokerServiceSetSpeedResponse);
  rpc StreamEvents(WinkeyerBrokerServiceStreamEventsRequest) returns (stream WinkeyerBrokerServiceStreamEventsResponse);
}
